sql_user={
   "getpic1":"select image_ponit from video where tid={tid}",
   "getpic2":"select image_ponit from scenic_spotty where tid={tid}",
   "getpic3":"select image_ponit from scenic_spotty where tid={tid}",
"getpic4":"select image_ponit from scenic_spotty where tid={tid}",
"getpic5":"select image_ponit from scenic_spotty where tid={tid}",
"getpic6":"select image_ponit from scenic_spotty where tid={tid}",
"getpic7":"select image_ponit from scenic_spotty where tid={tid}",
"getpic8":"select image_ponit from scenic_spotty where tid={tid}",
"getpic9":"select image_ponit from scenic_spotty where tid={tid}",
"getpic10":"select image_ponit from scenic_spotty where tid={tid}",
"getwords1":"select tintroduce from scenic_spotty where tid={tid}",
"getwords2":"select tintroduce from scenic_spotty where tid={tid}",
"getwords3":"select tintroduce from scenic_spotty where tid={tid}",
   "get1":"select tintroduce,taddress from scenic_spotty where tid={tid}",
"get2":"select tintroduce,taddress from scenic_spotty where tid={tid}",
"get3":"select tintroduce,taddress from scenic_spotty where tid={tid}",
   "rande":"SELECT * FROM scenic_spotty  ORDER BY  RAND() LIMIT 10 ",
}